DO $$
BEGIN
  CREATE TYPE "CancelRequestStatus" AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "cancelRequestStatus" "CancelRequestStatus" NOT NULL DEFAULT 'NONE',
ADD COLUMN IF NOT EXISTS "cancelReason" TEXT;

ALTER TABLE "DriverProfile"
ADD COLUMN IF NOT EXISTS "acceptanceRate" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS "cancellationRate" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "tier" TEXT NOT NULL DEFAULT 'BASIC';
